const levels = [
  ['Medium', 'Guide Bob', [
    ['Legacy code changes UI with innerHTML and stores expenses in global var. What should Bob migrate toward?', ['More innerHTML', 'React state and components that render from state', 'CSS animations only'], 1, 'React renders UI from state instead of mutating page fragments.'],
    ['Which instruction best starts Lab 1?', ['Modernize it', 'Inspect legacy behavior, propose React component plan, preserve filter, add-expense, and total behavior', 'Rewrite all files'], 1, 'Behavior and constraints help Bob make safe focused changes.'],
    ['Food expenses are 120 and 60. Bob filters Food. What filtered total should appear?', ['80', '180', '260'], 1, 'Filtered total includes visible Food expenses.'],
  ]],
  ['Hard', 'Validate Bob', [
    ['Bob adds an expense, list updates, but total does not. Best next prompt?', ['Looks good', 'Trace total calculation from React state, fix stale calculation, rerun browser validation', 'Delete total'], 1, 'Trace broken state path, fix it, validate again.'],
    ['Which browser-validation prompt is strongest?', ['Test it', 'Open local app, filter Food, add Lunch for 120, verify new row and total, report expected versus observed', 'Check browser console'], 1, 'Precise flow and checks make validation repeatable.'],
    ['Why preserve legacy behavior during migration?', ['React requires old bugs', 'Modernization should improve code structure without silently breaking user workflows', 'Browser tool needs tables'], 1, 'Code can change radically; workflows users depend on remain.'],
  ]],
]

const shared = [
  ['1. What does legacy app do?', 'Start at legacy Expense Tracker. It is old JavaScript app that records spending. Filter Food, then add an expense. What can user see before any modernization?', 'Four observations: fields in form, category filter behavior, expense row, and Food total of $180.', ['Food total is $180', 'Page title looks modern', 'React components exist'], [0], 'Open public/legacy/index.html. Select Food. Confirm total is $180. Add any Food expense and note new visible row and total.'],
  ['2. What should you ask Bob before edits?', 'Bob is AI coding assistant. Before it changes code, which request best makes sure it understands app?', 'Bob explains visible behavior, where old code lives, and what could break. No files changed yet.', ['Inspect legacy files and visible behavior first; do not edit yet', 'Start rewriting code immediately', 'Ask only for a new page design'], [0], 'In Bob Agent mode, ask it to inspect legacy/index.html and legacy/app.js, list visible behavior and risks, preserve add/filter/list/total behavior, and make no edits yet.'],
  ['3. What must Bob plan prove?', 'Bob should propose plan before coding. Which plan is safe to approve? “One source of truth” means one reliable list of expenses used by whole app.', 'Plan names React components, one expense list in state, unchanged legacy app, and browser test.', ['One expense list controls page; total uses filtered expenses; legacy stays unchanged', 'Keep old inline onclick handlers', 'Replace page without checking user behavior'], [0], 'Read Bob plan. Approve only if it keeps legacy folder unchanged, uses one React expense list, calculates total from selected category, and names browser acceptance test.'],
  ['4. What should modern app contain?', 'After you approve plan, Bob creates React version. React builds page from data and components instead of manually changing HTML. Which result is correct?', 'Modern app has labelled form, category filter, list, total, and stable test IDs Bob can use to find controls.', ['Separate form, filter, list, and summary components with test IDs', 'One global var that changes HTML directly', 'Only a new visual design'], [0], 'Tell Bob to implement approved React app in modern/. Open it and confirm form, category filter, expense list, and total are visible with labelled controls.'],
  ['5. How will Bob prove app works?', 'Ask Bob to open modern app in browser. It must click and type like user, not edit code or hidden page data to claim success. Which is valid acceptance test?', 'Browser evidence: Lunch row visible and Food total changes from $180 to $300.', ['Open app, add Lunch for $120 in Food, filter Food, verify row and $300 total', 'Change React state directly', 'Only check page title'], [0], 'Ask Bob to open modern app in browser, add Lunch with amount 120 in Food, select Food filter, then report whether Lunch appears and total is $300.'],
  ['6. What happens when test fails?', 'If browser test fails, do not guess. Which Bob action finds cause, fixes it, and proves repair?', 'Short report: cause, changed file, and passing repeated browser test.', ['Trace data into total display, make smallest fix, repeat same browser test', 'Delete feature that failed', 'Say test is close enough'], [0], 'Ask Bob to trace expense data into total display, explain root cause, change smallest responsible file, then repeat exact Lunch/Food browser test.'],
]

const adaptations = {
  Core: ['', '', '', '', '', ''],
  Stretch: ['', ' Add one constraint about empty or invalid input.', ' Require empty and validation states.', ' Decide where validation feedback belongs.', ' Add one edge case.', ' Identify broken invariant and smallest responsible component.'],
  Expert: [' Define observable behavior contract plus one boundary case.', ' Add your own scope boundary and request migration risks.', ' Challenge state ownership and rendering choices.', ' Require Bob rationale for component responsibilities and test hooks.', ' Add a negative or boundary assertion.', ' Require failed invariant, root cause, patch scope, and proof.'],
}

const lab2ByGroup = {
  Core: 'Core route: use workshop skill structure and follow provided acceptance checklist.',
  Stretch: 'Medium route: build two practical Bob skills, then use them to deliver Category Budgets.',
  Expert: 'Hard route: build same two Bob skills, then make them robust enough for real feature work.',
}

const lab2StepsByGroup = {
  Core: [
    'Create <code>.bob/skills/expense-feature-builder/SKILL.md</code>.',
    'Create <code>.bob/skills/expense-browser-validator/SKILL.md</code>.',
    'Use both skills to add Category Budgets, then have Bob validate in browser.',
  ],
}

const lab2ChallengesByGroup = {
  Stretch: [
    ['How do you enter Agent mode?', 'Skills need Agent mode so Bob can activate skills and edit project files.', 'Agent mode appears in Bob chat before you create the skill.', ['Click mode selector, click Agent, then confirm Agent is selected', 'Open Settings and change browser color', 'Create a skill from Ask mode'], [0], '1. In Bob chat, click mode selector left of message box.\n2. Click Agent.\n3. Confirm Agent is shown in chat.\nAlternative: type /agent and press Enter.'],
    ['How do you start Feature Builder skill?', 'Create the skill in project scope so the workshop team can use it.', 'Skill creation form is open with project scope and Bob permission enabled.', ['Bob Settings, Skills, +, set project scope and allow Bob', 'Create a global skill in terminal', 'Add instructions to package.json'], [0], '1. Click Bob Settings below chat.\n2. Click Skills in left sidebar.\n3. Click +.\n4. Set Skill Name to expense-feature-builder.\n5. Set Scope & Location to this workshop project.\n6. Turn on Allow Bob to use this skill.\n7. Keep the creation form open for next step.'],
    ['What instructions go in Feature Builder skill?', 'Skill needs a focused, repeatable workflow.', 'Instructions inspect first, plan, preserve current behavior, and report results.', ['Inspect, plan, wait for approval, implement approved scope, preserve behavior, report', 'Rewrite every project file', 'Change UI before inspecting app'], [0], '1. In Description, type: Implement or change Expense Tracker features while preserving current user behavior.\n2. In Skill Instructions, paste:\n---\nname: expense-feature-builder\ndescription: Implement or change Expense Tracker features while preserving current user behavior.\nuser-invocable: true\n---\n1. Inspect existing Expense Tracker behavior and relevant files.\n2. Propose smallest change and wait for approval.\n3. Implement only approved change.\n4. Preserve add expense, category filter, expense list, and displayed total.\n5. Report changed files and validation result.\n3. Click Create.\n4. Confirm expense-feature-builder appears in Skills list.'],
    ['How do you create Browser Validator skill?', 'Browser validation needs a separate reusable Bob workflow.', 'A project-level browser validator has its exact instructions saved.', ['Create project skill with visible-browser validation workflow', 'Use Feature Builder for browser testing', 'Add only a skill name with no description'], [0], '1. In Bob Settings > Skills, click +.\n2. Set Skill Name to expense-browser-validator.\n3. Set Scope & Location to this workshop project.\n4. Turn on Allow Bob to use this skill.\n5. In Description, type: Validate Expense Tracker user flows through visible browser interaction.\n6. In Skill Instructions, paste:\n---\nname: expense-browser-validator\ndescription: Validate Expense Tracker user flows through visible browser interaction.\nuser-invocable: true\n---\n1. Open the running Expense Tracker in browser.\n2. Perform requested flow using visible controls.\n3. Compare expected result with observed result.\n4. Report pass or failure with evidence.\n7. Click Create.\n8. Confirm expense-browser-validator appears in Skills list.'],
    ['How do you verify skill activation?', 'Explicit invocation lets you see Bob load the validator instructions.', 'Bob loads expense-browser-validator before it tests the app.', ['Type /expense-browser-validator, select suggestion, request validation, approve expected tools', 'Ask Bob to guess a skill', 'Close Bob chat and open a terminal'], [0], '1. Return to Bob chat.\n2. Type /expense-browser-validator.\n3. Click expense-browser-validator suggestion.\n4. Type: Validate the current Expense Tracker add and filter flow.\n5. Approve Bob requests to use skill and browser actions.\n6. Confirm Bob says validator skill is active and reports visible test result.'],
    ['How do you build and prove Category Budgets?', 'Feature Builder implements; Browser Validator proves result through user flow.', 'Food budget persists after refresh and shows remaining or warning state.', ['Invoke both skills, implement budgets, then run Food budget browser flow', 'Only restyle page', 'Check Git history'], [0], '1. In Bob chat, type /expense-feature-builder and select suggestion.\n2. Type: Add Category Budgets to Expense Tracker. Users must set a category budget, see spent and remaining amounts, receive an over-budget warning, and keep budget data after refresh.\n3. Review Bob plan. Approve expected file edits only.\n4. Type /expense-browser-validator and select suggestion.\n5. Type: Open Expense Tracker. Set Food budget. Add a Food expense. Refresh page. Verify budget remains, remaining amount updates, and warning appears after spending exceeds budget.\n6. Approve expected browser actions.\n7. Record Bob expected-versus-observed report.'],
  ],
  Expert: [
    ['How do you enter Agent mode?', 'Hard skill work needs Agent mode before you create or invoke skills.', 'Agent mode is selected in Bob chat.', ['Click mode selector, click Agent, confirm Agent is selected', 'Open Ask mode and edit files', 'Use browser settings'], [0], '1. In Bob chat, click mode selector left of message box.\n2. Click Agent.\n3. Confirm Agent is shown in chat before continuing.'],
    ['How do you create scoped Feature Builder skill?', 'Project scope makes this skill available to workshop participants through version control.', 'Feature Builder creation form uses workshop project scope.', ['Open Bob Settings > Skills > +, set name and project scope, enable Bob', 'Create global skill only', 'Add skill details to browser address bar'], [0], '1. Click Bob Settings below chat.\n2. Click Skills in left sidebar.\n3. Click +.\n4. Set Skill Name to expense-feature-builder.\n5. Set Scope & Location to this workshop project.\n6. Turn on Allow Bob to use this skill.\n7. Keep the creation form open.'],
    ['What activation rule should Feature Builder use?', 'A precise description limits automatic activation to correct work.', 'Description includes Expense Tracker feature work and excludes unrelated or browser-only work.', ['Expense Tracker features only; exclude unrelated and browser-only validation', 'Every Bob conversation', 'Browser tests only'], [0], '1. In the open Feature Builder form, click Description.\n2. Type exactly: Implement or change Expense Tracker features; do not use for unrelated tasks or browser-only validation.\n3. Leave the form open for Skill Instructions.'],
    ['What Feature Builder instructions should you save?', 'Hard route requires inspection, approval, accessibility, and scoped implementation.', 'Saved instructions define inspection, plan, implementation, and reporting rules.', ['Inspect and plan first; preserve behavior; use semantic UI and test IDs', 'Refactor every component', 'Skip labels to save time'], [0], '1. Click Skill Instructions.\n2. Paste:\n---\nname: expense-feature-builder\ndescription: Implement or change Expense Tracker features; do not use for unrelated tasks or browser-only validation.\nuser-invocable: true\n---\n1. Inspect existing behavior, components, state ownership, accessibility needs, and migration risks.\n2. Propose a plan with changed files and acceptance criteria. Wait for approval.\n3. Make the smallest scoped change.\n4. Preserve add expense, category filter, list, and displayed total.\n5. Use semantic controls, accessible labels, and stable data-testid values.\n6. Report changed files, risks, and validation results.\n3. Click Create.\n4. Confirm expense-feature-builder appears in Skills list.'],
    ['How do you create scoped Browser Validator skill?', 'Validator needs its own project-level activation rule.', 'Browser Validator creation form is configured for this workshop.', ['Create a project skill named expense-browser-validator with Bob enabled', 'Reuse Feature Builder as the only skill', 'Create an unnamed skill'], [0], '1. In Bob Settings > Skills, click +.\n2. Set Skill Name to expense-browser-validator.\n3. Set Scope & Location to this workshop project.\n4. Turn on Allow Bob to use this skill.\n5. In Description, type exactly: Validate Expense Tracker user flows through visible browser interaction only.'],
    ['What Browser Validator instructions should you save?', 'Hard route needs honest, reproducible visible-browser proof.', 'Saved instructions forbid direct state changes and require criteria, edge cases, and evidence.', ['Use visible controls only; define criteria; test happy path and edge case; report evidence', 'Test once without expected result', 'Only read console output'], [0], '1. Click Skill Instructions.\n2. Paste:\n---\nname: expense-browser-validator\ndescription: Validate Expense Tracker user flows through visible browser interaction only.\nuser-invocable: true\n---\n1. State acceptance criteria and expected results before testing.\n2. Open the running app in browser.\n3. Use only visible browser controls. Never change app state or page DOM directly.\n4. Test the requested happy path and edge case.\n5. Compare expected and observed results.\n6. On failure, report failed invariant, likely cause, and exact reproduction steps.\n3. Click Create.\n4. Confirm expense-browser-validator appears in Skills list.'],
    ['How do you invoke Feature Builder for exact budget task?', 'Explicit invocation proves the new skill loads before feature work.', 'Bob receives the full budget scope and waits for approval after planning.', ['Invoke /expense-feature-builder and provide budget requirements before approving edits', 'Ask Bob to redesign everything', 'Run browser test before feature exists'], [0], '1. Return to Bob chat.\n2. Type /expense-feature-builder and click its suggestion.\n3. Type: Add Category Budgets. Each category needs a budget limit, spent amount, remaining amount, over-budget warning, persistence after refresh, accessible labels, and stable data-testid selectors. Preserve Expense Tracker add, filter, list, and total behavior.\n4. Read Bob plan.\n5. Approve expected read, edit, and command requests only.'],
    ['How do you define required budget edge cases?', 'Expected results must be clear before browser validation.', 'Bob lists expected results for four named edge cases without editing.', ['Ask Bob for expected no-budget, exact-limit, over-limit, and refresh results', 'Start testing without expected results', 'Delete budget data'], [0], '1. After Bob finishes implementation, type: Before validation, list expected result for: 1. no budget set 2. spending exactly equals budget 3. spending exceeds budget 4. page refresh after budget entry. Do not edit files yet.\n2. Read all four expected results.\n3. If one is missing, ask Bob to add it before testing.'],
    ['How do you run full browser validation?', 'Validator must prove new budgets and original Lab 1 behavior through visible flows.', 'Bob reports expected and observed result for every requested flow.', ['Invoke validator and run four budget cases plus Lunch/Food regression', 'Change total text manually', 'Hide old expenses'], [0], '1. Type /expense-browser-validator and click its suggestion.\n2. Type: Open the running app and validate these visible browser flows: 1. no budget set 2. Food spending exactly equals Food budget 3. Food spending exceeds Food budget 4. refresh preserves budget data 5. add Lunch for $120 in Food, filter Food, verify Lunch row is visible and Food total is $300. Report expected and observed result for every flow.\n3. Approve expected browser actions.\n4. Record Bob report.'],
    ['How do you repair and improve skill?', 'Hard route ends with root-cause proof and a skill improvement.', 'Bob retests a focused fix, then the participant improves one unclear instruction.', ['Request root cause and retest; edit one vague skill instruction; test automatic activation', 'Mark task done after first failure', 'Delete failing scenario'], [0], '1. If a flow fails, type: State failed invariant, root cause, changed file, and smallest fix. Make the fix, then repeat only the failed browser flow.\n2. After all tests pass, click Bob Settings > Skills.\n3. Open each skill and rewrite one instruction that caused ambiguity.\n4. Click Save.\n5. Click + above Bob chat to start a new conversation.\n6. Ask for an Expense Tracker change without naming a skill.\n7. Confirm Bob proposes activating the matching skill from its description.'],
  ],
}

const app = document.querySelector('#app')
let stage = 0, question = 0, answers = [], scores = { medium: 0, hard: 0 }
let result = null
const saveResult = (value) => { try { localStorage.setItem('bob-workshop-diagnostic', JSON.stringify(value)) } catch {} }
const clearResult = () => { try { localStorage.removeItem('bob-workshop-diagnostic') } catch {} }

const esc = (value) => String(value).replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' })[char])
const groupFor = () => scores.medium < 2 ? 'Core' : scores.hard < 2 ? 'Stretch' : 'Expert'
const correct = (selected, required) => selected.length === required.length && required.every((item) => selected.includes(item))

function renderQuiz() {
  const [title, eyebrow, questions] = levels[stage]
  const current = questions[question]
  const selected = answers[question]
  const progress = Math.round(((stage * 3 + question + (selected !== undefined ? 1 : 0)) / 6) * 100)
  app.innerHTML = `<header class="hero"><p class="eyebrow">Refactor Revolution · IBM Bob</p><h1>Find your <span>Lab 1</span> route.</h1><p>Answer Bob-and-modernization questions. Guidance changes; participation does not.</p><div class="progress"><i style="width:${progress}%"></i></div></header><section class="quiz-card"><div class="quiz-meta"><span>${eyebrow}</span><span>${title} · ${question + 1} / 3</span></div><h2>${current[0]}</h2><div class="choices">${current[1].map((choice, index) => `<button class="choice ${selected === index ? (index === current[2] ? 'correct' : 'wrong') : ''}" data-answer="${index}">${choice}</button>`).join('')}</div>${selected !== undefined ? `<div class="feedback ${selected === current[2] ? 'good' : ''}"><strong>${selected === current[2] ? 'Correct.' : 'Not quite.'}</strong> ${current[3]}</div>` : ''}<div class="quiz-footer"><span>Each correct answer earns 1 point.</span>${selected !== undefined ? `<button id="next">${question === 2 ? (stage === 2 ? 'See route' : 'Continue') : 'Next question'}</button>` : ''}</div></section><section class="preview-flow"><p class="eyebrow">After your route</p><h2>Three blocks. One working app.</h2><p>Setup Bob. Modernize Expense Tracker to React. Create Bob skills that build and browser-validate Category Budgets.</p></section>`
  document.querySelectorAll('[data-answer]').forEach((button) => button.onclick = () => { if (answers[question] !== undefined) return; answers[question] = Number(button.dataset.answer); renderQuiz() })
  const next = document.querySelector('#next')
  if (next) next.onclick = () => { if (question < 2) { question++; renderQuiz(); return } const gained = answers.reduce((sum, answer, index) => sum + (answer === questions[index][2]), 0); scores[['medium', 'hard'][stage]] = gained; if ((stage === 0 && gained < 2) || stage === 1) { result = { group: groupFor(), scores }; saveResult(result); renderLab2Offer() } else { stage++; question = 0; answers = []; renderQuiz() } }
  const preview = app.querySelector('.preview-flow')
  preview.insertAdjacentHTML('beforeend', '<button class="guide-button" id="view-guide">View Lab 1 guide</button>')
  document.querySelector('#view-guide').onclick = renderLab1
}

function challengeHtml(challenge, index, group, includeAdaptation = true) {
  const [title, task, deliverable, choices] = challenge
  const adaptation = includeAdaptation ? adaptations[group]?.[index] || '' : ''
  return `<li class="lab-step"><div class="step-top"><span class="step-number">${String(index + 1).padStart(2, '0')}</span><div><h4>${title}</h4><p>${task}${adaptation}</p></div></div><div class="challenge" data-challenge="${index}"><p class="choice-hint">Choose one answer.</p>${choices.map((choice, choiceIndex) => `<button class="fragment" data-choice="${choiceIndex}">${esc(choice)}</button>`).join('')}<button class="check-button" data-check="${index}">Check answer</button><p class="challenge-result" hidden></p></div><p class="deliverable"><strong>What you should see:</strong> ${deliverable}</p></li>`
}

function renderGuide(previewGroup) {
  const group = previewGroup || result.group
  app.innerHTML = `<header class="hero compact"><p class="eyebrow">Refactor Revolution</p><h1>Your route: <span>${group}</span></h1><p>Same project. Different amount of guidance.</p></header><section class="route-grid"><article class="route ${group === 'Core' ? 'selected' : ''}"><h2>Core</h2><p>Exact milestones, visible hints, one change at a time.</p></article><article class="route ${group === 'Stretch' ? 'selected' : ''}"><h2>Stretch</h2><p>Partial requests. Choose boundaries and user experience.</p></article><article class="route ${group === 'Expert' ? 'selected' : ''}"><h2>Expert</h2><p>Outcome-led brief. Challenge Bob output and validation.</p></article></section><section class="workshop-flow"><div class="section-heading"><p class="eyebrow">Your workshop runbook</p><h2>Follow this page. No README hunt.</h2></div><article class="instruction-card setup"><span class="lab-number">00</span><div><p class="eyebrow">Setup · 30 minutes</p><h3>Prepare Bob and project</h3><ol><li>Open this folder in IBM Bob and trust workspace.</li><li>Select Agent mode so Bob can inspect files, run commands, and open browser.</li><li>Open <code>public/legacy/index.html</code> in browser.</li><li>Filter Food and add one expense to see current behavior.</li></ol></div></article><article class="instruction-card"><span class="lab-number">01</span><div><p class="eyebrow">Lab 1 · 30 minutes</p><h3>Modernize Expense Tracker</h3><p class="lab-intro">Each step has decision challenge. Fragments guide Bob request; no full prompt to copy.</p><ol class="lab-steps">${shared.map((item, index) => challengeHtml(item, index, group)).join('')}</ol></div></article><article class="instruction-card"><span class="lab-number">02</span><div><p class="eyebrow">Lab 2 · 30 minutes</p><h3>Teach Bob reusable skills</h3><ol><li>Create feature-builder and browser-validator skills in <code>.bob/skills/</code>.</li><li>Give skills clear activation description and ordered workflow.</li><li>Use them to add Category Budgets: limits, remaining amount, warning, and persistence.</li><li>Start fresh Bob conversation, invoke skills, then watch Bob validate in browser.</li></ol></div></article></section><div class="actions"><a class="secondary" href="public/legacy/index.html">Open legacy app</a><button class="text-button" id="reset">Retake diagnostic</button></div>`
  const selections = Array.from({ length: shared.length }, () => [])
  document.querySelectorAll('[data-choice]').forEach((button) => button.onclick = () => { const box = button.closest('[data-challenge]'), index = Number(box.dataset.challenge), choice = Number(button.dataset.choice); selections[index] = [choice]; box.querySelectorAll('[data-choice]').forEach((item) => item.classList.toggle('selected', Number(item.dataset.choice) === choice)) })
  document.querySelectorAll('[data-check]').forEach((button) => button.onclick = () => { const index = Number(button.dataset.check), message = button.parentElement.querySelector('.challenge-result'), required = shared[index][4], pass = correct(selections[index], required), missing = required.filter((choice) => !selections[index].includes(choice)).map((choice) => `“${shared[index][3][choice]}”`), remove = selections[index].filter((choice) => !required.includes(choice)).map((choice) => `“${shared[index][3][choice]}”`), advice = [remove.length ? `Remove: ${remove.join(', ')}.` : '', missing.length ? `Also select: ${missing.join(', ')}.` : ''].filter(Boolean).join(' '); message.hidden = false; message.textContent = pass ? `Correct. Do this now: ${shared[index][5]}` : `Almost there. ${advice} Then do this: ${shared[index][5]}`; message.className = `challenge-result ${pass ? 'pass' : ''}` })
  const reset = document.querySelector('#reset')
  reset.textContent = result ? 'Retake diagnostic' : 'Take diagnostic'
  reset.onclick = () => { clearResult(); stage = 0; question = 0; answers = []; scores = { medium: 0, hard: 0 }; result = null; renderQuiz() }
}

function renderLanding() {
  app.classList.add('landing')
  app.innerHTML = `<header class="hero"><img class="bob-logo" src="public/bob-logo.png" alt="IBM Bob" /><p class="eyebrow">Refactor Revolution · IBM Bob</p><h1>Welcome, <span>builder.</span></h1><p>Modernize a small legacy app, teach IBM Bob reusable skills, and watch it validate results in browser.</p><button class="guide-button" id="ready">I'm ready</button></header>`
  document.querySelector('#ready').onclick = renderLab1
}

function renderLab1() {
  app.classList.remove('landing')
  app.innerHTML = `<header class="hero compact"><img class="bob-logo" src="public/bob-logo.png" alt="IBM Bob" /><p class="eyebrow">Refactor Revolution · IBM Bob</p><h1>What will you do in <span>Lab 1</span>?</h1><p>No workshop knowledge needed. You will help IBM Bob modernize one small app, then watch it test result in browser.</p><div class="top-actions"><a class="secondary" href="public/legacy/index.html">Open legacy app</a></div></header><section class="workshop-flow"><div class="section-heading"><p class="eyebrow">Lab 1 · 30 minutes</p><h2>How will you modernize Expense Tracker?</h2><p class="lab-intro"><strong>Starting point:</strong> Expense Tracker is old browser app for recording spending. <strong>Finish line:</strong> same behavior in React, proved through Bob browser test. Each question tells you why it matters, what you do, and what evidence to show.</p></div><article class="instruction-card setup"><span class="lab-number">00</span><div><p class="eyebrow">Before you begin</p><h3>What do you need before starting?</h3><ol><li>Open this workshop folder in IBM Bob.</li><li>Select <strong>Agent</strong> mode. It lets Bob inspect files, edit code, and operate browser.</li><li>Open <code>public/legacy/index.html</code> to see old app.</li><li>Use buttons below each question to choose helpful request fragments. You write final Bob request yourself.</li></ol></div></article><article class="instruction-card"><span class="lab-number">01</span><div><p class="eyebrow">Modernize</p><h3>How will you work with IBM Bob?</h3><ol class="lab-steps">${shared.map((item, index) => challengeHtml(item, index, 'Core')).join('')}</ol></div></article></section><section class="preview-flow"><p class="eyebrow">Next</p><h2>Ready for adaptive checkpoint?</h2><p>Answer IBM Bob Lab 1 questions for recommended route, or view Lab 2 directly.</p><div class="top-actions"><button class="guide-button" id="start-quiz">Start adaptive quiz</button><button class="secondary" id="view-lab2">View Lab 2</button></div></section>`
  wireChallenges()
  document.querySelector('#view-lab2').onclick = renderQuizConfirmation
  document.querySelector('#start-quiz').onclick = () => { stage = 0; question = 0; answers = []; scores = { medium: 0, hard: 0 }; result = null; renderQuiz() }
}

function renderLab2Chooser() {
  app.innerHTML = `<header class="hero compact"><p class="eyebrow">Lab 2</p><h1>Choose your <span>guide</span>.</h1><p>Open Medium or Hard Lab 2 directly. No adaptive quiz required.</p></header><section class="route-grid"><button class="route" id="choose-medium"><h2>Medium</h2><p>Build practical Bob skills, then add and validate Category Budgets.</p></button><button class="route" id="choose-hard"><h2>Hard</h2><p>Build robust Bob skills with edge cases, regression testing, and skill improvement.</p></button></section><div class="actions"><button class="secondary" id="back-lab1">Back to Lab 1</button></div>`
  document.querySelector('#choose-medium').onclick = () => { result = { group: 'Stretch' }; renderLab2Offer(true) }
  document.querySelector('#choose-hard').onclick = () => { result = { group: 'Expert' }; renderLab2Offer(true) }
  document.querySelector('#back-lab1').onclick = renderLab1
}

function renderQuizConfirmation() {
  app.innerHTML = `<header class="hero compact"><p class="eyebrow">Before Lab 2</p><h1>Have you completed <span>adaptive quiz</span>?</h1><p>Quiz result recommends Medium or Hard Lab 2 guidance. You can still view either guide directly.</p></header><section class="preview-flow"><p class="eyebrow">Confirm</p><h2>Choose next action.</h2><div class="top-actions"><button class="guide-button" id="confirm-quiz">Yes, view Lab 2</button><button class="secondary" id="start-quiz-confirm">No, start quiz</button><button class="text-button" id="back-lab1">Back to Lab 1</button></div></section>`
  document.querySelector('#confirm-quiz').onclick = renderLab2Chooser
  document.querySelector('#start-quiz-confirm').onclick = () => { stage = 0; question = 0; answers = []; scores = { medium: 0, hard: 0 }; result = null; renderQuiz() }
  document.querySelector('#back-lab1').onclick = renderLab1
}

function wireChallenges(challenges = shared) {
  const selections = Array.from({ length: challenges.length }, () => [])
  document.querySelectorAll('[data-choice]').forEach((button) => button.onclick = () => { const box = button.closest('[data-challenge]'), index = Number(box.dataset.challenge), choice = Number(button.dataset.choice); selections[index] = [choice]; box.querySelectorAll('[data-choice]').forEach((item) => item.classList.toggle('selected', Number(item.dataset.choice) === choice)) })
  document.querySelectorAll('[data-check]').forEach((button) => button.onclick = () => { const index = Number(button.dataset.check), message = button.parentElement.querySelector('.challenge-result'), current = challenges[index], pass = correct(selections[index], current[4]), answer = `“${current[3][current[4][0]]}”`, action = current[5].replaceAll('\n3. Click Create.\n4. Confirm', '\nThen click Create.\nConfirm'), feedback = pass ? 'Correct.' : `Incorrect. Correct answer: ${answer}.`; message.hidden = false; message.innerHTML = `<p class="answer-feedback"><strong>${feedback}</strong></p><section class="next-action"><p class="next-action-title">Do this now</p><p class="action-steps">${esc(action)}</p></section>`; message.className = `challenge-result ${pass ? 'pass' : ''}` })
}

function renderLab2Offer(preview = false) {
  const group = result.group
  const challenges = lab2ChallengesByGroup[group]
  const content = challenges ? `<ol class="lab-steps">${challenges.map((challenge, index) => challengeHtml(challenge, index, group, false)).join('')}</ol>` : `<ol>${lab2StepsByGroup[group].map((step) => `<li>${step}</li>`).join('')}</ol>`
  app.innerHTML = `<header class="hero compact"><p class="eyebrow">${preview ? 'Lab 2 preview' : 'Adaptive result'}</p><h1>Lab 2: <span>${group}</span></h1><p>${preview ? 'Previewing selected Lab 2 guidance.' : 'Your Lab 1 result selected this level of guidance.'}</p></header><section class="route-grid"><article class="route ${group === 'Stretch' ? 'selected' : ''}"><h2>Stretch</h2><p>Medium guidance and design choices.</p></article><article class="route ${group === 'Expert' ? 'selected' : ''}"><h2>Expert</h2><p>Hard guidance and validation critique.</p></article></section><section class="workshop-flow"><article class="instruction-card"><span class="lab-number">02</span><div><p class="eyebrow">Lab 2 · 30 minutes</p><h3>Teach Bob reusable skills</h3><p class="lab-intro">${lab2ByGroup[group]}</p>${content}</div></article></section><div class="actions"><button class="secondary" id="back-lab1">Review Lab 1</button><button class="text-button" id="retake">Retake adaptive quiz</button></div>`
  if (challenges) wireChallenges(challenges)
  document.querySelector('#back-lab1').onclick = renderLab1
  document.querySelector('#retake').onclick = () => { stage = 0; question = 0; answers = []; scores = { medium: 0, hard: 0 }; result = null; renderQuiz() }
}

renderLanding()
